
name: Testing Application

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yml'
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml